### ISSUE TITLE
Change the "subgraph error" alert and add an "RPC error" alert

### ISSUE THREAD

**Issue by maxaleks** [xdaichain/omnibridge#212]
1. move the "subgraph error" alert to the History page (or is it necessary on the main page?) and make it less annoying. Especially if it blocks to perform bridging operations:

    ![image](https://user-images.githubusercontent.com/20793260/114765389-5971a100-9d22-11eb-9f55-cce650bbbc01.png)

    Here is an example how the similar message integrated within the xDai Bridge:

    ![image](https://user-images.githubusercontent.com/13244928/114750939-37494480-9d5d-11eb-9b48-fc0e8945a6b7.png)

2. Consider to add an "RPC error" alert. An example from the xDai Bridge:

    ![image](https://user-images.githubusercontent.com/13244928/114751006-4def9b80-9d5d-11eb-8fe5-87a1731e31d8.png)

**Comment by akolotov** [comment]
This is another example to display that the current way to report about the graph issue is not useful:
![image](https://user-images.githubusercontent.com/20793260/114845821-54036d80-9d99-11eb-8d30-8829a7247cf7.png)
Two of three messages reports about the same.

It makes sense to inform user about the graph issue only if it blocks users operations: e.g. if a user cannot claim tokens, or if they visit the history page etc. Otherwise the users starting claiming about the issues with the bridge even if they just visit the page or perform simple operations which should not be affected by absence of the graph data.
